# https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-apiversion-definition-guide.html
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: gateway-svc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-svc
      env: uat
  template:
    metadata:
        labels:
          app: gateway-svc
          env: uat
    spec:
      containers:
        - name: gateway-svc
          image: gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-port
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-svc
    env: uat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80